### PR TITLE
Renaming Rooms/Suspects/Weapons

### PR DESCRIPTION
**Pull request by chelsea0x3b**

### CODE REVIEW

**Comment by NebuchadnezzarXIII** [comment]
Corey, are we removing the getter that made use of strings to access the suspect? E.g. is Room.get("Hall") deprecated now?

**Comment by chelsea0x3b** [comment]
I wasn't planning on it, still need some way to access the values based on a string passed from the frontend. Do you think it should be deprecated?

**Comment by NebuchadnezzarXIII** [comment]
No, leaving it is perfect. I was just concerned that if we removed the get method that a lot of the code I wrote would need to be re-written.

**Review by NebuchadnezzarXIII — APPROVED** [review]
This will definitely make coordination between the front and back end much easier.

**Pull request merged**
