### PR TITLE
Accuse frontend

### PR DESCRIPTION
**Pull request by NebuchadnezzarXIII**
added frontend logic for accuse

### CODE REVIEW

**Comment by chelsea0x3b** [comment]
is this also branched off of the suggestion out of order PR?

**Comment by NebuchadnezzarXIII** [comment]
Oh yes, I remembered my original rationale for why I made the state changes serverside. So there were some logical branches that occured serverside that wouldn't have gotten noticed by the client so those needed messages to update what the client could do. And for the sake of having everything all in one place, I moved all the controls for whether the player could do something serverside instead of a mixed bag of server side and client side.

**Comment by chelsea0x3b** [comment]
what logical branches are those?

**Comment by NebuchadnezzarXIII** [comment]
so when you make a suggestion that nobody can disprove, only the server is capable of knowing that, and so has to send a notification to the player to allow them to end their turn.

**Comment by chelsea0x3b** [comment]
isn't there a notification sent out when no one can disprove?

**Comment by NebuchadnezzarXIII** [comment]
yeah but its a chat notification.

**Comment by NebuchadnezzarXIII** [comment]
So I could either tack some things onto chat notifications or send a seperate event.

**Comment by chelsea0x3b** [comment]
i think it should be a separate notification

**Review by chelsea0x3b — APPROVED** [review]

**Pull request merged**
