### PR TITLE
Makign rooms a flexbox, which spaces suspects out into rows

### PR DESCRIPTION
**Pull request by chelsea0x3b**

### CODE REVIEW

**Comment by zadeluca** [comment]
doesn't work 100% 
screenshot from 2016-12-07 12-10-58

**Comment by zadeluca** [comment]
actually that might be how you intended it? i dont think the box changed its size, does the room name in the upper right cause the last dot to go to the third row?

**Comment by chelsea0x3b** [comment]
yeah the name is causing that... Let me see If i can get the name on its own line

**Comment by chelsea0x3b** [comment]
Alright should be fixed now

**Review by zadeluca — APPROVED** [review]

**Pull request merged**
